version: "3.8"

services:
    mysql:
        container_name: mysql_v2
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        restart: always        
        volumes:
            - ./schema:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test
            MYSQL_USER: test
            MYSQL_PASSWORD: test
        ports:
            - "3306:3306"
        env_file: 
            - .env

    app:
        container_name: app_v2
        image: python:3.9
        links: 
            - "mysql:mysql"
        restart: always
        command: sh -c "cd /code && pip install -r requirements.txt && pip install uvicorn && uvicorn app:app --host 0.0.0.0 --port 8000"
        ports:
            - "8000:8000"
        volumes:
            - .:/code       
        env_file: 
            - .env
