version: "3.8"

services:
    mysql:
        container_name: mysql_1-2
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        restart: always        
        volumes:
            - ./schema:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test
            MYSQL_USER: test
            MYSQL_PASSWORD: test
        ports:
            - "3306:3306"
        env_file: 
            - .env

    app:
        container_name: app_1-2
        image: python:3.9
        links: 
            - "postgres:postgres"
        restart: always
        command: sh -c "cd /code && pip install -r requirements.txt && pip install uvicorn && uvicorn app:app --host 0.0.0.0 --port 80"
        ports:
            - "8080:80"
        volumes:
            - .:/code       
        env_file: 
            - .env

    postgres:
        image: postgres:latest
        container_name: postgres_1-2
        ports:
            - 5432:5432
        restart: always
        volumes: 
            - db_data:/var/lib/postgres/db_data
        environment: 
            POSTGRES_PASSWORD: root

volumes: 
    db_data: